spring:
  application:
    name: Od_Tasking
  servlet:
    multipart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  SECRET_KEY: ZklN7dQKtUB/eJHNKevcGXKr9GEh/CYGec9i0ZfkmQFeWUD0npk60wxnhMjS9xxu


file:
  upload-dir: src/main/resources/static/img


minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket-name: feedback-images